import Color from "../../util/color"
const styles={
    mainContainer:{
        backgroundColor:Color.lightgreen,
    },
    textmain:{
        fontSize:64,
        fontFamily:'Inter',
        fontWeight:700,
        textAlign:'center'
    },
    textdetail:{
        fontSize:16,
        fontWeight:400,
        fontFamily:'Inter',
        textAlign:'center',
        color:Color.gray
    },
    parentbutton:{
        display:'flex',
        alignContent:'center'
    },
    buttonMostPopular:{
        width:'34%',
        backgroundColor:Color.lightGreen,
        border:0,
        height:50,
        marginLeft:22
       
    },
    priceComTitle:{
        fontSize:24,
        fontFamily:'Inter',
        fontWeight:700,
        textAlign:'center'
    },
    priceComDetail:{
        fontSize:16,
        fontFamily:'Inter',
        fontWeight:400,
        textAlign:'center',
        color:Color.gray
    },
    price:{
        fontSize:48,
        fontFamily:'Inter',
        fontWeight:700,
        textAlign:'center'
    },
    buttonComPrice:{
        backgroundColor:'transparent',
        fontSize:16,
        color:Color.black,
        borderColor:Color.black,
        width:'100%'
    },
    ul:{
        listStyle:'none',
        
    },
    li:{
        display:'flex',
        flexDirection:'row'
    },
    pricing:{
        borderColor:Color.mediumPrimary
    },
    i:{
        fontSize:16,
        color:Color.black,
        marginRight:20,
        marginTop:20
    },
    lidetail:{
        fontSize:16,
        color:Color.gray,
        fontWeight:700,
        fontFamily:'Inter',
        marginTop:18,
    },
    row:{
        display:'flex',
        justifyContent:'center',
        padding: 2,
    },
    spacingRow:{
        marginTop:60
    }
}
export default styles